### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by FrancisBanville** [FrancisBanville/academic-kickstart#1]
# Website 
- [x] Update skills (emphasis on programming language) 
- [x] Add links to ORCID, Linkedin, ResearchGate, Google Scholar 
- [ ] Add links to Poisot lab, Gravel lab, IVADO, QCBS, BIOS2
- [ ] Add experiences
- [ ] Add accomplishments
- [ ] Add talks
- [x] Add publications
- [ ] Add funding
- [ ] Add teaching experiences
- [ ] Add nice photos

# Miscellaneous
- [ ] Update CV
